## Tarea M35-AD - Bryan Alberto Coronado García

### Importar el archivo “supermarket_sales.csv”

In [1]:
# Importación de librerías

import os
import numpy as np
import pandas as pd

# Verificación de ruta de trabajo

os.chdir('/Users/bryancoronado/Desktop/EBAC/TAREAS (Python Avanzado)/Tarea M35 (Numpy)')
os.getcwd()

In [2]:
# Chequeo de DataFrame

df = pd.read_csv('supermarket_sales.csv')
df.sample(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
732,756-49-0168,A,Yangon,Member,Male,Fashion accessories,19.70,1,0.9850,20.6850,2/8/2019,11:39,Ewallet,19.70,4.761905,0.9850,9.5
512,595-27-4851,A,Yangon,Normal,Female,Fashion accessories,54.28,7,18.9980,398.9580,1/27/2019,18:05,Ewallet,379.96,4.761905,18.9980,9.3
681,320-85-2052,B,Mandalay,Normal,Female,Sports and travel,34.81,1,1.7405,36.5505,1/14/2019,10:11,Credit card,34.81,4.761905,1.7405,7.0
225,746-68-6593,C,Naypyitaw,Member,Female,Sports and travel,87.16,2,8.7160,183.0360,1/11/2019,14:29,Credit card,174.32,4.761905,8.7160,9.7
44,617-15-4209,C,Naypyitaw,Member,Male,Health and beauty,15.37,2,1.5370,32.2770,3/16/2019,19:47,Cash,30.74,4.761905,1.5370,7.2

### Importar la librería NumPy. Generar estadística descriptiva básica en las columnas unit_price y quantity: Cálculo de la media, mediana, moda

In [3]:
# Conversión de columnas a arrays

unit_price_np = df[['Unit price']].to_numpy()
quantity_np = df[['Quantity']].to_numpy()

# Comprobación del tipo de los arrays y sus contenidos

print('Verificación de las clases de los dos arrays:\n')
print(type(quantity_np))
print(type(unit_price_np),'\n')
print('Verificación del contenido de los arrays:\n')
print(unit_price_np[0:10,0])
print(quantity_np[0:10,0])

Verificación de las clases de los dos arrays:

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

Verificación del contenido de los arrays:

[74.69 15.28 46.33 58.22 86.31 85.39 68.84 73.56 36.26 54.84]
[ 7  5  7  8  7  7  6 10  2  3]

In [4]:
# Estadísticas del array 'Unit Price'

vals1, counts1 = np.unique(unit_price_np, return_counts=True)
moda = vals1[np.argmax(counts1)]
median1 = np.median(unit_price_np)
mean1 = np.mean(unit_price_np)

print('Las estadísticas básicas del Unit Price son las siguientes:\n')
print(f'La moda del array "Unit Price" equivale a {moda:.2f}')
print(f'La mediana del array "Unit Price" corresponde a {median1:.2f}')
print(f'La media del array "Unit Price" sería {mean1:.2f}\n')
print('-' * 60)

# Estadísticas del array 'Quantity'

vals2, counts2 = np.unique(quantity_np, return_counts=True)
moda2 = vals2[np.argmax(counts2)]
median2 = np.median(quantity_np)
mean2 = np.mean(quantity_np)

print('Las estadísticas básicas del Unit Price son las siguientes:\n')
print(f'La moda del array "Quantity" equivale a {moda2:.1f}')
print(f'La mediana del array "Quantity" corresponde a {median2:.1f}')
print(f'La media del array "Quantity" sería {mean2:.1f}')
print('-' * 60)

Las estadísticas básicas del Unit Price son las siguientes:

La moda del array "Unit Price" equivale a 83.77
La mediana del array "Unit Price" corresponde a 55.23
La media del array "Unit Price" sería 55.67

------------------------------------------------------------
Las estadísticas básicas del Unit Price son las siguientes:

La moda del array "Quantity" equivale a 10.0
La mediana del array "Quantity" corresponde a 5.0
La media del array "Quantity" sería 5.5
------------------------------------------------------------

### Tickets promedio

In [5]:
# 1) Ticket promedio por ciudad
print("Ticket promedio por ciudad:\n")
ticket_ciudad = df.groupby('City')['Total'].mean().reset_index()
print(ticket_ciudad, '\n')
print("-" * 50)

# 2) Ticket promedio por product line y ciudad
print("Ticket promedio por product line y ciudad:\n")
ticket_product_city = df.groupby(['Product line', 'City'])['Total'].mean().reset_index()
print(ticket_product_city, '\n')
print("-" * 50)

# 3) Ticket promedio por género
print("Ticket promedio por género:\n")
ticket_gender = df.groupby('Gender')['Total'].mean().reset_index()
print(ticket_gender, '\n')
print("-" * 50)

# 4) Ticket promedio por género y product line
print("\nTicket promedio por género y product line:\n")
ticket_gender_product = df.groupby(['Gender', 'Product line'])['Total'].mean().reset_index()
print(ticket_gender_product, '\n')
print("-" * 50)

Ticket promedio por ciudad:

        City       Total
0   Mandalay  319.872506
1  Naypyitaw  337.099715
2     Yangon  312.354031

--------------------------------------------------
Ticket promedio por product line y ciudad:

              Product line       City       Total
0   Electronic accessories   Mandalay  310.026245
1   Electronic accessories  Naypyitaw  344.890445
2   Electronic accessories     Yangon  305.285225
3      Fashion accessories   Mandalay  264.730911
4      Fashion accessories  Naypyitaw  331.693385
5      Fashion accessories     Yangon  320.245265
6       Food and beverages   Mandalay  304.297770
7       Food and beverages  Naypyitaw  360.103864
8       Food and beverages     Yangon  295.915526
9        Health and beauty   Mandalay  376.993585
10       Health and beauty  Naypyitaw  319.525500
11       Health and beauty     Yangon  268.037298
12      Home and lifestyle   Mandalay  350.983290
13      Home and lifestyle  Naypyitaw  308.790067
14      Home and lifestyle     Yangon  344.879931
15       Sports and travel   Mandalay  322.390306
16       Sports and travel  Naypyitaw  350.265067
17       Sports and travel     Yangon  328.350839

--------------------------------------------------
Ticket promedio por género:

   Gender       Total
0  Female  335.095659
1    Male  310.789226

--------------------------------------------------

Ticket promedio por género y product line:

    Gender            Product line       Total
0   Female  Electronic accessories  322.643125
1   Female     Fashion accessories  317.056250
2   Female      Food and beverages  368.565750
3   Female       Health and beauty  290.015414
4   Female      Home and lifestyle  380.213639
5   Female       Sports and travel  324.712739
6     Male  Electronic accessories  316.691965
7     Male     Fashion accessories  291.079207
8     Male      Food and beverages  273.499125
9     Male       Health and beauty  348.099460
10    Male      Home and lifestyle  294.136241
11    Male       Sports and travel  340.360327

--------------------------------------------------

### Top 5:

In [39]:
def analizar_top_ventas(dataframe, columna_categoria, top_n=6):

    total_sales = dataframe['Total'].sum()

    ventas_por_categoria = dataframe.groupby(columna_categoria)['Total'].sum().reset_index()
    ventas_por_categoria.columns = [columna_categoria, 'Sales']

    ventas_por_categoria['Rank'] = ventas_por_categoria['Sales'].rank(ascending=False) # Calculo de rango

    top_categorias = ventas_por_categoria[ventas_por_categoria['Rank'] < top_n].sort_values(by='Rank') # Top 5

    top_categorias['% Contribution'] = round((top_categorias['Sales'] / total_sales) * 100,2) # Porcentaje de contribución

    return top_categorias

# 1) Top 5 ventas por ciudad
print("Top 5 ventas por ciudad:\n")
top_5_cities = analizar_top_ventas(df, 'City')
print(top_5_cities, '\n')
print("-" * 50)

# 2) Top 5 ventas por tipo de cliente
print("Top 5 ventas por tipo de cliente:\n")
top_5_customer = analizar_top_ventas(df, 'Customer type')
print(top_5_customer, '\n')
print("-" * 50)

# 3) Top 5 ventas por método de pago
print("Top 5 ventas por método de pago:\n")
top_5_payments = analizar_top_ventas(df, 'Payment')
print(top_5_payments, '\n')
print("-" * 50)

Top 5 ventas por ciudad:

        City        Sales  Rank  % Contribution
1  Naypyitaw  110568.7065   1.0           34.24
2     Yangon  106200.3705   2.0           32.88
0   Mandalay  106197.6720   3.0           32.88

--------------------------------------------------
Top 5 ventas por tipo de cliente:

  Customer type       Sales  Rank  % Contribution
0        Member  164223.444   1.0           50.85
1        Normal  158743.305   2.0           49.15

--------------------------------------------------
Top 5 ventas por método de pago:

       Payment       Sales  Rank  % Contribution
0         Cash  112206.570   1.0           34.74
2      Ewallet  109993.107   2.0           34.06
1  Credit card  100767.072   3.0           31.20

--------------------------------------------------

### Cálculo de una matriz de correlación entre la hora (sin minutos) y el total, y otra que correlacione el unit_price con el rating de la transacción

In [65]:
# Conversión de columna Time a 'datetime' y después extracción sin minutos
df['Time'] = pd.to_datetime(df['Time'])
df['Hora'] = df['Time'].dt.hour

print("Muestra del DataFrame a tratar:")
print(df[['Hora', 'Total', 'Unit price', 'Rating']].sample(5))
print("-" * 50)

# Calcular las matrices de correlación
matriz_corr_hora_total = df[['Hora', 'Total']].corr()
matriz_corr_unit_price_rating = df[['Unit price', 'Rating']].corr()

print("Matriz de correlación entre 'Hora' y 'Total':\n")
print(round(matriz_corr_hora_total,3))
print("-" * 50)

print("Matriz de correlación entre 'Unit Price' y 'Rating':\n")
print(round(matriz_corr_unit_price_rating,3))
print("-" * 50, '\n')

print('// No existe correlación entre las variables solicitadas // \n')

Muestra del DataFrame a tratar:
     Hora     Total  Unit price  Rating
685    12  103.1100       49.10     6.4
144    16  491.0850       77.95     8.0
326    19  523.8450       99.78     5.4
130    13  291.2070       39.62     7.5
156    19   75.7785       72.17     6.1
--------------------------------------------------
Matriz de correlación entre 'Hora' y 'Total':

        Hora  Total
Hora   1.000 -0.003
Total -0.003  1.000
--------------------------------------------------
Matriz de correlación entre 'Unit Price' y 'Rating':

            Unit price  Rating
Unit price       1.000  -0.009
Rating          -0.009   1.000
--------------------------------------------------

// No existe correlación entre las variables solicitadas //